Reduce bytes-like support to only bytes and bytearray
Other bytes-like objects lose the guarantee of being null-terminated
which many points of the decoder rely on to detect truncated inputs.
This allows the decoder to read past the end of its input for as long as
the trash memory afterwards still looks like valid JSON:

    >>> ujson.loads(array.array("b", b'"truncated')[:3])
    ujson.JSONDecodeError: Found UTF-8 continuation byte without corresponding start byte when decoding 'string'

We could smother everything in bounds checking but for the sake of not
over-complicating things souly for one feature that was more a byproduct
of bytearray support anyway, just block such types. This effectively
makes the PyPy path the only path.